### ISSUE TITLE
Skins don't work

### ISSUE THREAD

**Issue by ThatsNotAName** [ThatsNotAName/KoaLeahq-Skins#2]
Nimi Sora V1 doesn't work and Nimi Sora V2 is just nimi Sora V1 so yeah get on it, @Arokomi 

https://github.com/ThatsNotAName/KoaLeahq-Skins/blob/master/Koa-skins.md#koaligmaniimi-sorav2

**Comment by Arok573** [comment]
V1 outdated so I remove it, V2 has minor tweaks and bug fixes but pracitcally looks the same.
